-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 18:25:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bda_ws1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bda_ws1` ;

-- -----------------------------------------------------
-- Schema bda_ws1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bda_ws1` DEFAULT CHARACTER SET utf8 ;
USE `bda_ws1` ;

-- -----------------------------------------------------
-- Table `bda_ws1`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` YEAR NOT NULL,
  `semester` INT NOT NULL,
  `month` INT NULL DEFAULT NULL,
  `day` INT NULL DEFAULT NULL,
  `weekday` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`student` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`lecturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`lecturers_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`lecturers_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lecturer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `lecturer_id`),
  INDEX `fk_lecturers_group_lecturer1_idx` (`lecturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_lecturers_group_lecturer1`
    FOREIGN KEY (`lecturer_id`)
    REFERENCES `bda_ws1`.`lecturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`course` (
  `code` VARCHAR(25) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `program` VARCHAR(45) NOT NULL,
  `lecturing_hours` INT NOT NULL,
  `exercise_hours` INT NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`exam_taken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`exam_taken` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `lecturers_group_id` INT NOT NULL,
  `course_code` VARCHAR(25) NOT NULL,
  `exam_id` INT NOT NULL,
  `score` DOUBLE NOT NULL,
  `count` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_exam_taken_time_idx` (`time_id` ASC) VISIBLE,
  INDEX `fk_exam_taken_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_lecturers_group_idx` (`lecturers_group_id` ASC) VISIBLE,
  INDEX `fk_exam_taken_course1_idx` (`course_code` ASC) VISIBLE,
  INDEX `fk_exam_taken_exam1_idx` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_exam_taken_time`
    FOREIGN KEY (`time_id`)
    REFERENCES `bda_ws1`.`time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_taken_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `bda_ws1`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecturers_group`
    FOREIGN KEY (`lecturers_group_id`)
    REFERENCES `bda_ws1`.`lecturers_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_taken_course1`
    FOREIGN KEY (`course_code`)
    REFERENCES `bda_ws1`.`course` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_taken_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `bda_ws1`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`program` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `faculty` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registration_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_registration_program1_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_registration_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `bda_ws1`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registration_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `bda_ws1`.`program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(25) NOT NULL,
  `lecturers_group_id` INT NOT NULL,
  `time_id` INT NOT NULL,
  `delivery` DOUBLE NOT NULL,
  `content` DOUBLE NOT NULL,
  `overall` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evaluation_course1_idx` (`course_code` ASC) VISIBLE,
  INDEX `fk_evaluation_lecturers_group1_idx` (`lecturers_group_id` ASC) VISIBLE,
  INDEX `fk_evaluation_time1_idx` (`time_id` ASC) VISIBLE,
  CONSTRAINT `fk_evaluation_course1`
    FOREIGN KEY (`course_code`)
    REFERENCES `bda_ws1`.`course` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_lecturers_group1`
    FOREIGN KEY (`lecturers_group_id`)
    REFERENCES `bda_ws1`.`lecturers_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_time1`
    FOREIGN KEY (`time_id`)
    REFERENCES `bda_ws1`.`time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`semester` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` YEAR NOT NULL,
  `semester` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda_ws1`.`course_evaluated`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bda_ws1`.`course_evaluated` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(25) NOT NULL,
  `student_id` INT NOT NULL,
  `semester_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_evaluated_course1_idx` (`course_code` ASC) VISIBLE,
  INDEX `fk_course_evaluated_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_course_evaluated_semester1_idx` (`semester_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_evaluated_course1`
    FOREIGN KEY (`course_code`)
    REFERENCES `bda_ws1`.`course` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_evaluated_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `bda_ws1`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_evaluated_semester1`
    FOREIGN KEY (`semester_id`)
    REFERENCES `bda_ws1`.`semester` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
