insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (1, 'Introduction to Psychology', 3, 2, 6);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (2, 'History of Art', 2, 2, 13);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (3, 'Computer Science 101', 2, 2, 23);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (4, 'English Literature', 3, 2, 28);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (5, 'Mathematics for Beginners', 3, 3, 15);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (6, 'Chemistry Fundamentals', 3, 1, 12);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (7, 'Business Ethics', 3, 2, 28);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (8, 'Environmental Science', 1, 2, 34);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (9, 'Music Theory', 3, 3, 20);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (10, 'Introduction to Sociology', 2, 3, 25);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (11, 'Political Science', 3, 2, 7);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (12, 'Economics Principles', 3, 2, 3);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (13, 'Digital Marketing Strategies', 2, 3, 10);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (14, 'Creative Writing Workshop', 3, 1, 9);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (15, 'Physics for Non-Science Majors', 2, 3, 37);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (16, 'Public Speaking', 3, 2, 29);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (17, 'Introduction to Philosophy', 2, 3, 10);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (18, 'Health and Wellness', 1, 1, 29);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (19, 'Graphic Design Basics', 3, 1, 38);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (20, 'Foreign Language Studies', 3, 3, 18);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (21, 'Culinary Arts', 2, 1, 11);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (22, 'Film Studies', 3, 3, 39);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (23, 'Engineering Design', 1, 1, 21);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (24, 'Theater Production', 1, 1, 34);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (25, 'Sports Management', 1, 3, 12);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (26, 'Fashion Merchandising', 1, 2, 23);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (27, 'Nutrition and Dietetics', 1, 1, 21);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (28, 'Journalism and Media Studies', 1, 1, 11);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (29, 'Interior Design Principles', 1, 1, 11);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (30, 'Human Resource Management', 2, 2, 15);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (31, 'Cybersecurity Fundamentals', 3, 3, 32);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (32, 'Artificial Intelligence Applications', 2, 1, 25);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (33, 'Biotechnology Innovations', 3, 2, 27);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (34, 'Global Studies', 3, 2, 26);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (35, 'Entrepreneurship and Innovation', 3, 1, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (36, 'Social Work Practice', 1, 2, 22);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (37, 'Urban Planning and Development', 3, 2, 32);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (38, 'Forensic Science', 2, 3, 8);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (39, 'Healthcare Administration', 1, 2, 34);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (40, 'Music Production Techniques', 2, 3, 33);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (41, 'Psychological Counseling', 3, 3, 8);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (42, 'Sustainable Energy Solutions', 2, 3, 29);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (43, 'Marine Biology', 2, 2, 37);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (44, 'Fashion Design Concepts', 3, 3, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (45, 'Public Relations Strategies', 1, 3, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (46, 'Data Analytics for Business', 1, 2, 10);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (47, 'Robotics and Automation', 1, 3, 9);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (48, 'Astronomy Discoveries', 1, 1, 9);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (49, 'Legal Studies', 3, 3, 24);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (50, 'Travel and Tourism Management', 2, 2, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (51, 'Renewable Energy Technologies', 2, 2, 14);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (52, 'Graphic Novel Illustration', 3, 1, 24);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (53, 'Human Rights Advocacy', 2, 3, 14);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (54, 'Event Planning and Management', 2, 3, 32);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (55, 'Child Development Theories', 3, 2, 11);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (56, 'Game Design Fundamentals', 1, 3, 7);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (57, 'Environmental Policy Analysis', 3, 1, 33);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (58, 'Sports Nutrition', 3, 2, 34);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (59, 'Music History', 3, 2, 7);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (60, 'Political Campaign Strategies', 2, 1, 18);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (61, 'Health Informatics', 3, 2, 27);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (62, 'Art Therapy Techniques', 3, 1, 4);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (63, 'Criminal Justice System', 1, 1, 36);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (64, 'Digital Photography', 3, 1, 3);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (65, 'Advertising and Branding', 1, 2, 10);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (66, 'Biomedical Engineering', 3, 2, 1);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (67, 'Gender Studies', 1, 3, 28);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (68, 'Real Estate Finance', 1, 3, 32);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (69, 'Animation and Visual Effects', 3, 3, 20);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (70, 'Social Media Marketing', 1, 1, 9);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (71, 'Public Health Issues', 1, 3, 24);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (72, 'Theology and Religious Studies', 3, 2, 23);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (73, 'Fashion Retail Management', 3, 3, 36);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (74, 'Supply Chain Logistics', 1, 1, 32);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (75, 'Film Production', 3, 3, 17);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (76, 'Industrial Psychology', 2, 1, 31);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (77, 'Food Science and Technology', 3, 2, 7);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (78, 'Music Education Methods', 3, 2, 21);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (79, 'International Business Law', 2, 3, 1);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (80, 'Environmental Engineering', 2, 1, 11);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (81, 'Dance Performance', 2, 2, 36);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (82, 'Human Anatomy and Physiology', 3, 1, 19);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (83, 'Web Development Fundamentals', 3, 2, 3);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (84, 'Cognitive Neuroscience', 1, 3, 24);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (85, 'Hospitality Management', 3, 1, 27);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (86, 'Fine Arts Appreciation', 1, 1, 34);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (87, 'Conflict Resolution Strategies', 3, 1, 3);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (88, 'Aviation Management', 2, 3, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (89, 'Organizational Behavior', 1, 3, 25);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (90, 'Mobile App Development', 2, 1, 4);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (91, 'Veterinary Medicine', 3, 3, 14);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (92, 'Social Justice Movements', 1, 1, 31);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (93, 'Fashion Marketing Strategies', 2, 1, 22);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (94, 'Renewable Resource Management', 2, 2, 22);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (95, 'Music Therapy Practices', 1, 1, 2);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (96, 'Political Economy Analysis', 1, 1, 31);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (97, 'Healthcare Ethics', 3, 3, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (98, 'Interior Architecture Design', 2, 1, 25);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (99, 'Sports Psychology', 1, 2, 35);
insert into course (code, name, lecturing_hours, exercise_hours, program_id) values (100, 'Fashion Styling Techniques', 3, 3, 32);
