INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE CIENCIAS BIOLÓGICAS", 2);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE CIENCIAS ECONÓMICAS", 4);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE CIENCIAS POLÍTICAS", 7);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE CIENCIAS DE LA COMPUTACIÓN", 2);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE INGENIERÍA CIVIL", 9);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE INGENIERÍA ELÉCTRICA YELECTRÓNICA", 9);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE LINGÜÍSTICA", 5);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE MATEMÁTICAS", 2);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE QUÍMICA", 2);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE PSICOLOGÍA", 5);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE ARQUITECTURA", 1);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE DERECHO", 6);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE CIENCIAS DE LA EDUCACIÓN", 5);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE MEDICINA", 10);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE ARTES PLÁSTICAS", 1);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE GEOCIENCIAS", 2);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE MÚSICA", 1);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE CIENCIAS AGRARIAS", 3);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE SOCIOLOGÍA", 5);
INSERT INTO department (name, faculty_id) VALUES ("DEPARTAMENTO DE FÍSICA", 2);