insert into program (id, name, department_id) values (1, 'ADMINISTRACIÓN DE EMPRESAS', 14);
insert into program (id, name, department_id) values (2, 'ANTROPOLOGÍA', 18);
insert into program (id, name, department_id) values (3, 'ARQUITECTURA', 6);
insert into program (id, name, department_id) values (4, 'ARTES PLÁSTICAS', 1);
insert into program (id, name, department_id) values (5, 'BIOLOGÍA', 11);
insert into program (id, name, department_id) values (6, 'CIENCIA POLÍTICA', 7);
insert into program (id, name, department_id) values (7, 'CIENCIAS DE LA COMPUTACIÓN', 18);
insert into program (id, name, department_id) values (8, 'CINE Y TELEVISIÓN*', 18);
insert into program (id, name, department_id) values (9, 'CONTADURÍA PÚBLICA', 11);
insert into program (id, name, department_id) values (10, 'DERECHO', 11);
insert into program (id, name, department_id) values (11, 'DISEÑO GRÁFICO', 4);
insert into program (id, name, department_id) values (12, 'DISEÑO INDUSTRIAL', 14);
insert into program (id, name, department_id) values (13, 'ECONOMÍA', 1);
insert into program (id, name, department_id) values (14, 'ENFERMERÍA', 10);
insert into program (id, name, department_id) values (15, 'ESPAÑOL Y FILOLOGÍA LÁSICA', 20);
insert into program (id, name, department_id) values (16, 'ESTADÍSTICA', 16);
insert into program (id, name, department_id) values (17, 'FARMACIA', 4);
insert into program (id, name, department_id) values (18, 'FILOLOGÍA E IDIOMAS: ALEMÁN', 1);
insert into program (id, name, department_id) values (19, 'FILOLOGÍA E IDIOMAS: RANCÉS', 18);
insert into program (id, name, department_id) values (20, 'FILOLOGÍA E IDIOMAS: INGLÉS', 16);
insert into program (id, name, department_id) values (21, 'FILOSOFÍA', 8);
insert into program (id, name, department_id) values (22, 'FÍSICA', 6);
insert into program (id, name, department_id) values (23, 'FISIOTERAPIA', 12);
insert into program (id, name, department_id) values (24, 'GEOGRAFÍA', 10);
insert into program (id, name, department_id) values (25, 'GEOLOGÍA', 11);
insert into program (id, name, department_id) values (26, 'INGENIERÍA AGRÍCOLA', 5);
insert into program (id, name, department_id) values (27, 'INGENIERÍA AGRONÓMICA', 14);
insert into program (id, name, department_id) values (28, 'INGENIERÍA CIVIL', 20);
insert into program (id, name, department_id) values (29, 'INGENIERÍA DE ISTEMAS Y COMPUTACIÓN', 6);
insert into program (id, name, department_id) values (30, 'INGENIERÍA ELÉCTRICA', 10);
insert into program (id, name, department_id) values (31, 'INGENIERÍA ELECTRÓNICA', 12);
insert into program (id, name, department_id) values (32, 'INGENIERÍA NDUSTRIAL', 19);
insert into program (id, name, department_id) values (33, 'INGENIERÍA MECÁNICA', 10);
insert into program (id, name, department_id) values (34, 'INGENIERÍA MECATRÓNICA', 15);
insert into program (id, name, department_id) values (35, 'INGENIERÍA QUÍMICA', 6);
insert into program (id, name, department_id) values (36, 'LINGÜÍSTICA', 2);
insert into program (id, name, department_id) values (37, 'MATEMÁTICAS', 9);
insert into program (id, name, department_id) values (38, 'MEDICINA', 15);
insert into program (id, name, department_id) values (39, 'MEDICINA VETERINARIA', 8);
insert into program (id, name, department_id) values (40, 'MÚSICA* (COMPOSICIÓN, IRECCIÓN, INVESTIGACIÓN EN PEDAGOGÍA INSTRUMENTAL, JAZZ)', 12);
insert into program (id, name, department_id) values (41, 'MÚSICA INSTRUMENTAL *( ARPA CLÁSICA, ANTO, CLARINETE, CONTRABAJO, CORNO, EUFONIO, FAGOT, FLAUTA, GUITARRA, OBOE, PERCUSIÓN, PIANO, SAXOFÓN, TROMBÓN, TROMPETA, TUBA, VIOLA, VIOLÍN, VIOLONCHEL', 11);
